cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
	path('add/<int:product_id>/', views.add_cart, name='add_cart'),
	path('', views.cart_detail, name='cart_detail'),
	path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
	path('full_remove/<int:product_id>/', views.full_remove, name='full_remove'),
]

order/urls.py
from django.urls import path
from . import views

app_name='order'

urlpatterns = [
	path('thanks/<int:order_id>/', views.thanks, name='thanks'),
	path('history/', views.orderHistory, name='order_history'),
	path('<int:order_id>/', views.viewOrder, name='order_detail'),
]

poofy/urls.py
from django.contrib import admin
from django.urls import path, include
from shop import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('shop/', include('shop.urls')), #this includes all the urls of the shop app
    path('search_app/', include('search_app.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('account/create/', views.signupView, name='signup'),
    path('account/login/', views.signinView, name='signin'),
    path('account/logout/', views.signoutView, name='signout'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    #you are mapping the static and media urls, follow the imported settings and static files 
    
    

search_app/urls.py
from django.urls import path
from . import views

app_name = 'search_app'

urlpatterns = [
  path('', views.searchResult, name='searchResult'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
  path('', views.allProdCat, name='allProdCat'),
  path('<slug:c_slug>/', views.allProdCat, name='products_by_category'),# this name is used in models.py
  path('<slug:c_slug>/<slug:product_slug>/', views.ProdCatDetail, name='ProdCatDetail'), #this name is also used in models.py

]

shop/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
  name = models.CharField(max_length=250, unique=True)
  slug = models.SlugField(max_length=250, unique=True) #this is the url field
  description= models.TextField(blank=True)
  image = models.ImageField(upload_to='category', blank=True)

  class Meta:
    ordering = ('name',)
    verbose_name = 'category'
    verbose_name_plural = 'categories'

  def get_url(self):
    return reverse('shop:products_by_category', args=[self.slug])

  def __str__(self):
    return '{}'.format(self.name)
  
class Product(models.Model):
  name = models.CharField(max_length=250, unique=True)
  slug = models.SlugField(max_length=250, unique=True)
  description= models.TextField(blank=True)
  category = models.ForeignKey(Category, on_delete= models.CASCADE) #if deleted, CASCADE will delete any reference of the Category model
  price = models.DecimalField(max_digits=10, decimal_places=2)
  image = models.ImageField(upload_to='product', blank=True)
  stock = models.IntegerField()
  available = models.BooleanField(default=True)
  created = models.DateTimeField(auto_now_add=True)
  updated = models.DateTimeField(auto_now=True)

  class Meta:
    ordering = ('name',)
    verbose_name = 'product'
    verbose_name_plural = 'products'

  def get_url(self):
    return reverse('shop:ProdCatDetail', args=[self.category.slug, self.slug])

  def __str__(self):
    return '{}'.format(self.name)

shop/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
	first_name = forms.CharField(max_length=100, required=True)
	last_name = forms.CharField(max_length=100, required=True)
	email = forms.EmailField(max_length=254, help_text='eg. youremail@anyemail.com')

	class Meta:
		model = User
		fields = ('first_name','last_name','email','username','password1','password2')

shop/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from .models import Category,Product
from django.core.paginator import Paginator, EmptyPage, InvalidPage
from django.contrib.auth.models import Group, User
from .forms import SignUpForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate, logout

def index(request):
  text_var = 'my first django web page'
  return HttpResponse(text_var)

#view for Category

def allProdCat(request, c_slug=None):
  c_page = None
  products_list = None
  if c_slug != None:
    c_page = get_object_or_404(Category, slug=c_slug)
    products_list = Product.objects.filter(category=c_page, available=True)
  else:
    products_list = Product.objects.all().filter(available=True)
  # code for pagination below
  paginator = Paginator(products_list, 6)
  try:
    page = int(request.GET.get('page', '1'))
  except:
    page = 1
  try:
    products = paginator.page(page)
  except (EmptyPage, InvalidPage):
    products = paginator.page(paginator.num_pages)

  return render(request, 'shop/category.html', {'category':c_page,'products':products})

def ProdCatDetail(request, c_slug, product_slug):
  try:
    product = Product.objects.get(category__slug=c_slug, slug = product_slug) #double underscore after category will utilize the foreign key in the model before checking for slug in category__slug
  except Exception as e:
    raise e
  return render(request, 'shop/product.html', {'product': product})

def signupView(request):
	if request.method == 'POST':
		form = SignUpForm(request.POST)
		if form.is_valid():
			form.save()
			username = form.cleaned_data.get('username')
			signup_user = User.objects.get(username=username)
			customer_group = Group.objects.get(name='Customer')
			customer_group.user_set.add(signup_user)
	else:
		form = SignUpForm()
	return render(request, 'accounts/signup.html', {'form':form})

def signinView(request):
	if request.method == 'POST':
		form = AuthenticationForm(data=request.POST)
		if form.is_valid():
			username = request.POST['username']
			password = request.POST['password']
			user = authenticate(username=username, password=password)
			if user is not None:
				login(request, user)
				return redirect('shop:allProdCat')
			else:
				return redirect('signup')
	else:
		form = AuthenticationForm()
	return render(request,'accounts/signin.html', {'form':form })

def signoutView(request):
	logout(request)
	return redirect('signin')

shop/templates/base.html
{% load staticfiles %}
<!-- make sure you load staticfiles or you will get a TemplateSyntaxError -->
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- 1. acquire the viewport meta tag from getboostrap.com -->
  <meta name="description" content="{% block metadescription %} {% endblock %}">
  <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet"> 
  <link rel="stylesheet" href="{% static 'css/custom.css' %}"> 
  <!-- placing custom.css above bootstrap.min.css will grant it priority -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"> 
  <!-- 2. Insert the django static pack in href via the word static prior to the location within static, also put the location in single quotes -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/fontawesome-all.min.css' %}">
  <title>{% block title %}{% endblock %}</title>
</head>

<body>
  <div class="container">
    <div class="container-fluid bg-light navbar-fixed-top my_top_navbar_div">
      {% include 'top-navbar.html' %}
    </div>
    {% include 'header.html' %}
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}
  </div>
    {% include 'footer.html' %}
  <script src="{% static 'js/jquery-3.3.1.slim.min.js' %}" ></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <!-- the above 3 files are taken from the bootstrap cdn but their code was copy-pasted into static/js, thus I reference it to that location -->
</body>

</html>

shop/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
  <p class="text-center">This site was made with the Django Framework, and is running from an Amazon EC2 server.</p>
</div>

shop/templates/header.html
{% load staticfiles %}
<header>
  <center>
    <a href="{% url 'shop:allProdCat' %}" ><img src="{% static 'img/logo.png' %}" alt="Poofy Paradise"></a>
  </center>
</header>

shop/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown {% if 'shop' in request.path %}active{% endif %}">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Shop
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'shop:allProdCat' %}">All Products</a>
            {% for cat in links %}
            <a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a>
            {% endfor %}
          </div>
        </li>
        {% if item_count > 0 %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'cart:cart_detail' %}"><i class="fas fa-shopping-cart"></i>({{item_count}})</a>
        </li>
      {% endif %}
    </ul>
    <form class="form-inline my-2 my-lg-0" action="{% url 'search_app:searchResult' %}" method="get">
      {% csrf_token %}
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
      <button class="btn btn-secondary my-2 my-sm-0" type="submit"><i class="fas fa-search"></i></button>
    </form>
  </div>
</nav>

shop/templates/top-navbar.html
<div class="container">
	<div class="my_custom_menu">
		<ul>
			{% if request.user.is_authenticated and request.user.first_name %}
			<li>
				Welcome, <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ request.user.first_name }} <i class="fas fa-user-circle"></i></a>
					<div class="dropdown-menu dropdown-menu-right">
						<a href="{% url 'order:order_history' %}" class="dropdown-item">Order History</a>
					</div>
			</li>
			<li>
				<a href="{% url 'signout' %}">Sign Out <i class="fas fa-sign-out-alt"></i></a>
			</li>
			{% else %}
			<li>
				<a href="{% url 'signup' %}">Sign Up <i class="fas fa-user-plus"></i></a>
			</li>
			<li>
				<a href="{% url 'signin' %}">Sign In <i class="fas fa-sign-in-alt"></i></a>
			</li>
			{% endif %}
		</ul>
		
	</div>
</div>