cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
	path('add/<int:product_id>/', views.add_cart, name='add_cart'),
	path('', views.cart_detail, name='cart_detail'),
	path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
	path('full_remove/<int:product_id>/', views.full_remove, name='full_remove'),
]

poofy/urls.py
from django.contrib import admin
from django.urls import path, include
from shop import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('shop/', include('shop.urls')), #this includes all the urls of the shop app
    path('search_app/', include('search_app.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('account/create/', views.signupView, name='signup'),
    path('account/login/', views.signinView, name='signin'),
    path('account/logout/', views.signoutView, name='signout'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    #you are mapping the static and media urls, follow the imported settings and static files 
    
    

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
  path('', views.allProdCat, name='allProdCat'),
  path('<slug:c_slug>/', views.allProdCat, name='products_by_category'),# this name is used in models.py
  path('<slug:c_slug>/<slug:product_slug>/', views.ProdCatDetail, name='ProdCatDetail'), #this name is also used in models.py

]

cart/models.py
from django.db import models
from shop.models import Product

class Cart(models.Model):
  cart_id = models.CharField(max_length=250, blank=True)
  date_added = models.DateField(auto_now_add=True)
  class Meta:
    db_table = 'Cart'
    ordering = ['date_added']
  
  def __str__(self):
    return self.cart_id
  
class CartItem(models.Model):
  product = models.ForeignKey(Product, on_delete=models.CASCADE)
  cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
  quantity = models.IntegerField()
  active = models.BooleanField(default=True)
  class Meta:
    db_table = 'CartItem'

  def sub_total(self):
    return self.product.price * self.quantity
  
  def __str__(self):
    return self.product

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from shop.models import Product
from . models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist
import stripe
from django.conf import settings
from order.models import Order, OrderItem
from django.template.loader import get_template
from django.core.mail import EmailMessage


def _cart_id(request):
  cart = request.session.session_key
  if not cart:
    cart = request.session.create()
  return cart

def add_cart(request, product_id):
  product = Product.objects.get(id=product_id)
  try:
    cart = Cart.objects.get(cart_id=_cart_id(request))
  except Cart.DoesNotExist:
    cart = Cart.objects.create(
      cart_id = _cart_id(request)
    )
    cart.save(),
  try:
    cart_item = CartItem.objects.get(product=product, cart=cart)
    if cart_item.quantity < cart_item.product.stock:
      cart_item.quantity += 1
    cart_item.save()
  except CartItem.DoesNotExist:
    cart_item = CartItem.objects.create(
      product = product,
      quantity = 1,
      cart = cart
    )
  cart_item.save()
  return redirect('cart:cart_detail')

def cart_detail(request, total=0, counter=0, cart_items= None):
  try:
    cart = Cart.objects.get(cart_id=_cart_id(request))
    cart_items = CartItem.objects.filter(cart=cart, active=True)
    for cart_item in cart_items:
      total += (cart_item.product.price * cart_item.quantity)
      counter += cart_item.quantity
  except ObjectDoesNotExist:
    pass

  stripe.api_key = settings.STRIPE_SECRET_KEY
  stripe_total = int(total * 100)
  description = 'New Order'
  data_key = settings.STRIPE_PUBLISHABLE_KEY
  if request.method == 'POST':
    # print(request.POST)
    try:
      token = request.POST['stripeToken']
      email = request.POST['stripeEmail']
      billingName = request.POST['stripeBillingName']
      billingAddress1 = request.POST['stripeBillingAddressLine1']
      billingcity = request.POST['stripeBillingAddressCity']
      billingPostcode = request.POST['stripeBillingAddressZip']
      billingCountry = request.POST['stripeBillingAddressCountryCode']
      shippingName = request.POST['stripeShippingName']
      shippingAddress1 = request.POST['stripeShippingAddressLine1']
      shippingcity = request.POST['stripeShippingAddressCity']
      shippingPostcode = request.POST['stripeShippingAddressZip']
      shippingCountry = request.POST['stripeShippingAddressCountryCode']
      customer = stripe.Customer.create(
          email=email,
          source = token
        )
      charge = stripe.Charge.create(
          amount=stripe_total,
          currency="usd",
          description=description,
          customer=customer.id
        )
      # I create the order here
      try:
        order_details = Order.objects.create(
            token = token,
            total = total,
            emailAddress = email,
            billingName = billingName,
            billingAddress1 = billingAddress1,
            billingCity = billingcity,
            billingPostcode = billingPostcode,
            billingCountry = billingCountry,
            shippingName = shippingName,
            shippingAddress1 = shippingAddress1,
            shippingCity = shippingcity,
            shippingPostcode = shippingPostcode,
            shippingCountry = shippingCountry
          )
        order_details.save()
        for order_item in cart_items:
          oi = OrderItem.objects.create(
              product = order_item.product.name,
              quantity = order_item.quantity,
              price = order_item.product.price,
              order = order_details
            )
          oi.save()
          # Reduce stock when order is placed or saved
          products = Product.objects.get(id=order_item.product.id)
          products.stock = int(order_item.product.stock - order_item.quantity)
          products.save()
          order_item.delete()
          # terminal confirmation when saved
          print('The order has been created')
        try:
          '''Calling the sendEmail function'''
          sendEmail(order_details.id)
          print('The order email has been sent to the customer.')
        except IOError as e:
          return e
        return redirect('order:thanks', order_details.id)
        # return redirect('shop:allProdCat')
      except ObjectDoesNotExist:
        pass
    except stripe.error.CardError as e:
      return False,e
  return render(request, 'cart.html', dict(cart_items = cart_items, total = total, counter = counter, data_key = data_key, stripe_total = stripe_total, description = description))


def cart_remove(request, product_id):
	cart = Cart.objects.get(cart_id=_cart_id(request))
	product = get_object_or_404(Product, id=product_id)
	cart_item = CartItem.objects.get(product=product, cart=cart)
	if cart_item.quantity > 1:
		cart_item.quantity -= 1
		cart_item.save()
	else:
		cart_item.delete()
	return redirect('cart:cart_detail')

def full_remove(request, product_id):
	cart = Cart.objects.get(cart_id=_cart_id(request))
	product = get_object_or_404(Product, id=product_id)
	cart_item = CartItem.objects.get(product=product, cart=cart)
	cart_item.delete()
	return redirect('cart:cart_detail')

def sendEmail(order_id):
	transaction = Order.objects.get(id=order_id)
	order_items = OrderItem.objects.filter(order=transaction)
	try:
		'''Sending the order'''
		subject = "Poofy Paradise - New Order #{}".format(transaction.id)
		to = ['{}'.format(transaction.emailAddress)]

		from_email = "receipt@poofyparadise.com"
		# from_email = '%s' % settings.EMAIL_HOST_USER # gmail only

		order_information = {
		'transaction' : transaction,
		'order_items' :	order_items
		}
		message = get_template('email/email.html').render(order_information)
		msg = EmailMessage(subject, message, to=to, from_email=from_email)
		msg.content_subtype = 'html'
		msg.send()
	except IOError as e:
		return e

cart/templates/cart.html
{% extends "base.html" %}
{% load staticfiles %}
{% block metadescription %}
	Shopping Cart - Review and submit your order.
{% endblock %}
{% block title %}
	Cart - Poofy Paradise
{% endblock %}
{% block content %}
	{% if not cart_items %}
		<div>
			<div class="text-center">
				<br>
				<h1 class="text-center my_title">
					Cart is empty.
				</h1>
				<br>
				<p class="text-center">
					Click <a href="{% url 'shop:allProdCat' %}">here</a> to continue shopping.
				</p>
			</div>
		</div>
	{% else %}
		<div>
			<div class="text-center">
				<br>
				<h1 class="text-center my_title">
					Your shopping cart
				</h1>
				<br>
			</div>
		</div>
		<div class="row mx-auto">
			<div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
				<table class="table my_custom_table">
					<thead class="my_custom_thead">
						<tr>
							<th colspan="5">
								Your items
							</th>
						</tr>
						
					</thead>
					<tbody>
						{% for cart_item in cart_items %}
							<tr>
								<td>
									<a href="{{cart_item.product.get_url}}"><img src="{{cart_item.product.image.url}}" alt="" class="float-left rounded custom_image"></a>
								</td>
								<td class="text-left">
									{{cart_item.product.name}}
									<br>
									SKU: {{cart_item.product.id}}
									<br>
									Unit Price: ${{cart_item.product.price}}
									<br>
									Qty: {{cart_item.quantity}} x ${{cart_item.product.price}}
								</td>
								<td>
									${{cart_item.sub_total}}
								</td>
								{% if cart_item.quantity < cart_item.product.stock %}
									<td>
										<a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a"><i class="fas fa-plus-circle custom_icon"></i></a>&nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fas fa-minus-circle custom_icon"></i></a>&nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fas fa-trash-alt custom_icon"></i></a>
									</td>
								{% else %}
									<td>
										&nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fas fa-minus-circle custom_icon"></i></a>&nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fas fa-trash-alt custom_icon"></i></a>
									</td>
									<td></td>
								{% endif %}
							</tr>
						{% endfor %}
					</tbody>
				</table>
				
			</div>
			<div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
				<table class="table my_custom_table">
					<thead class="my_custom_thead">
						<tr>
							<th>
								Checkout
							</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>
								Review your shopping cart here prior to placing your order.
							</td>
						</tr>
						<tr>
							<td class="text-left">
								Total: <strong>${{ total }}</strong>
							</td>
						</tr>
					</tbody>
				</table>
				<div class="mx-auto">
					<form action="" method="POST">
						{% csrf_token %}
					  <script
					    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
					    data-key="{{ data_key }}"
					    data-amount="{{ stripe_total }}"
					    data-name="Poofy Paradise"
					    data-description="{{ description }}"
					    data-image="{% static 'img/logo.png' %}"
					    data-locale="auto"
					    data-currency="usd"
					    data-shipping-address="true"
					    data-billing-address="true"
					    data-zip-code="true">
					  </script>
					</form>
					<a href="{% url 'shop:allProdCat' %}" class="btn btn-secondary btn-block my_custom_button">Continue Shopping</a>
				</div>
			</div>
		</div>
		<br>
	{% endif %}
{% endblock %}